// AIDA Locksmith Acquisition — the shared vocabulary (A1).
//
// Every enum the acquisition pipeline uses, in one place, with the reasoning
// for the ones whose values are load-bearing. Modules import from here rather
// than repeating string literals, so a typo is a missing export (loud) instead
// of a silently unmatched comparison (quiet, and in this domain, dangerous).
//
// Pure + dep-free. See test/acquisition-schema.test.js.

const SCHEMA_VERSION = "acq-1";

// ── Where a prospect came from ──────────────────────────────────────

// How a candidate business entered the system. This is provenance, and it is
// recorded permanently: "how did AIDA come to be calling this business?" must
// be answerable years later.
//
// Note what is NOT here: there is no "scraped" or "purchased" origin. This
// build cannot crawl and does not accept bought lists — a purchased list is
// exactly the artefact the permanent acquisition principle forbids.
const DISCOVERY_ORIGINS = Object.freeze([
  "fixture", // the deterministic in-repo dataset (tests, dry run)
  "manual_entry", // a human typed this business in, with a source
  "operator_import", // a file a human assembled and attested to
  "inbound_referral", // the business contacted AIDA first, or was referred
]);

const DISCOVERY_ORIGIN_LABELS = Object.freeze({
  fixture: "Built-in test dataset",
  manual_entry: "Entered by hand",
  operator_import: "Imported from an operator file",
  inbound_referral: "Came to us / referred",
});

// ── Source authority ────────────────────────────────────────────────

// The kind of place a fact about a business came from. Tiering matters because
// the pipeline requires an OFFICIAL source before a business may be called: a
// phone number copied off an aggregator is exactly how you end up dialling a
// number that has been reassigned, or a business that closed two years ago.
const SOURCE_TYPES = Object.freeze([
  "government_register", // ABR / ASIC — the strongest identity evidence
  "official_website", // the business's own site
  "verified_directory", // a directory that verifies listings
  "unverified_directory", // a directory that does not
  "aggregator", // scraped/compiled third-party listing site
  "social_profile", // Facebook / Instagram page
  "map_listing", // a maps pin
  "unknown", // provenance not established
]);

const SOURCE_TYPE_LABELS = Object.freeze({
  government_register: "Government business register",
  official_website: "The business's own website",
  verified_directory: "Verified trade directory",
  unverified_directory: "Unverified directory listing",
  aggregator: "Third-party aggregator",
  social_profile: "Social media profile",
  map_listing: "Map listing",
  unknown: "Unknown source",
});

// Sources that count as OFFICIAL for the purpose of the pipeline's "official
// business source identified" step. Everything else may support a record but
// can never be the only thing standing behind a call.
const OFFICIAL_SOURCE_TYPES = Object.freeze(["government_register", "official_website"]);

// Ranked strongest → weakest. Used to pick the primary source when a prospect
// has several, and to explain the choice to a human.
const SOURCE_AUTHORITY_ORDER = Object.freeze([
  "government_register",
  "official_website",
  "verified_directory",
  "map_listing",
  "unverified_directory",
  "social_profile",
  "aggregator",
  "unknown",
]);

// ── Evidence ────────────────────────────────────────────────────────

// What a single piece of captured evidence asserts. Evidence is the spine of
// the whole design: a prospect is not "a row we found", it is "a claim plus the
// proof we hold for it".
const EVIDENCE_KINDS = Object.freeze([
  "business_name", // the trading name as published
  "legal_name", // registered entity name
  "abn", // Australian Business Number
  "phone", // a published contact number
  "address", // a published address
  "service_area", // stated coverage
  "trade_category", // that it is, in fact, a locksmith
  "website", // the official site itself
  "operating_status", // evidence the business is still trading
]);

const EVIDENCE_KIND_LABELS = Object.freeze({
  business_name: "Business name",
  legal_name: "Registered legal name",
  abn: "ABN",
  phone: "Phone number",
  address: "Address",
  service_area: "Service area",
  trade_category: "Trade category",
  website: "Website",
  operating_status: "Still trading",
});

// How the evidence was obtained. Recorded on every row so a fixture-derived
// claim can never be mistaken for something a human actually verified.
const CAPTURE_MODES = Object.freeze([
  "fixture", // generated by the in-repo dataset
  "operator_entry", // a human typed what they saw
  "operator_import", // read from an operator-supplied file
  "live_fetch", // reserved; unavailable in this build
]);

// The evidence a prospect MUST hold before a human is even allowed to approve
// it for calling. Fewer than this and the review packet refuses to present an
// approve option (see acquisition-review.js).
const REQUIRED_EVIDENCE_KINDS = Object.freeze(["business_name", "phone", "trade_category"]);

// ── Prospect lifecycle ──────────────────────────────────────────────

// The states a prospect moves through. One-way except for the explicit
// re-review path: a rejected prospect can be reopened by a human, but nothing
// automatic ever promotes a prospect back toward callable.
//
// TWO HALVES, ONE MACHINE (M8B).
// The first six states are the ACQUISITION half — how a business became a
// record we believe in. The states after `review_approved` are the ENGAGEMENT
// half — what happened when we approached it. They are one machine rather than
// two because the question "may this business be contacted?" has to be
// answerable from a single value; a prospect with `lifecycle: review_approved`
// and a separate `engagement: not_interested` is a record with two answers, and
// the wrong one eventually wins.
//
// The engagement states are named for what is TRUE about the relationship, not
// for what a dialler did. `attempted` is a fact about us; `connected` is a fact
// about the call; `interested` / `not_interested` are facts about them.
const PROSPECT_STATES = Object.freeze([
  "discovered", // exists, nothing verified
  "evidence_captured", // has evidence attached, not yet reviewed
  "review_pending", // queued for a human
  "review_approved", // a human accepted the identity + source
  "review_rejected", // a human refused it
  // ── engagement (M8B) — nothing here places a call ──
  "queued", // selected into an approved calling batch; dormant
  "attempted", // a call was attempted and did not reach a person
  "connected", // a person answered
  "callback_requested", // they asked us to try again at a stated time
  "interested", // they want to hear more
  "not_interested", // they declined — re-approach needs remediation
  "customer", // they became an AIDA client
  "disqualified", // we decided not to pursue (not their decision)
  "suppressed", // permanently excluded (opt-out, blacklist, …)
]);

const PROSPECT_STATE_LABELS = Object.freeze({
  discovered: "Found, nothing checked yet",
  evidence_captured: "Evidence collected, waiting for review",
  review_pending: "Waiting for a human to review",
  review_approved: "Reviewed and accepted",
  review_rejected: "Reviewed and rejected",
  queued: "Waiting in an approved calling queue",
  attempted: "We tried to call and did not reach anyone",
  connected: "We spoke to someone",
  callback_requested: "They asked us to call back",
  interested: "Interested — wants to hear more",
  not_interested: "Not interested",
  customer: "Became an AIDA client",
  disqualified: "We decided not to pursue this business",
  suppressed: "Permanently excluded",
});

// States in the engagement half. Useful to the read model and to the queue,
// which must never re-queue a business that has already reached an answer.
const ENGAGEMENT_STATES = Object.freeze([
  "queued",
  "attempted",
  "connected",
  "callback_requested",
  "interested",
  "not_interested",
  "customer",
  "disqualified",
]);

// Legal transitions. Everything not listed is refused — the state machine is a
// whitelist, because "how did this become callable?" must have exactly one
// answer per step.
const PROSPECT_TRANSITIONS = Object.freeze({
  discovered: Object.freeze(["evidence_captured", "suppressed"]),
  evidence_captured: Object.freeze(["review_pending", "suppressed"]),
  review_pending: Object.freeze(["review_approved", "review_rejected", "suppressed"]),
  // A human may reopen their own decision; nothing else may. `queued` is the
  // ONLY forward step, and reaching it requires an approved batch and a passing
  // eligibility decision — see acquisition-queue.js.
  review_approved: Object.freeze(["review_pending", "queued", "disqualified", "suppressed"]),
  review_rejected: Object.freeze(["review_pending", "suppressed"]),

  // ── engagement ──
  // A queued prospect can be released back to the approved pool (the batch was
  // revoked, the lease expired, eligibility flipped) — releasing must always be
  // possible, or a queue bug strands records forever.
  queued: Object.freeze(["attempted", "review_approved", "disqualified", "suppressed"]),
  // An attempt that reached nobody. Re-queueing is normal here and is still
  // subject to the attempt policy's caps and spacing at selection time.
  attempted: Object.freeze(["connected", "queued", "callback_requested", "not_interested", "disqualified", "suppressed"]),
  connected: Object.freeze(["interested", "not_interested", "callback_requested", "customer", "disqualified", "suppressed"]),
  callback_requested: Object.freeze(["queued", "connected", "not_interested", "disqualified", "suppressed"]),
  interested: Object.freeze(["customer", "not_interested", "callback_requested", "disqualified", "suppressed"]),
  // "No" is not a temporary state. Re-approaching someone who declined is
  // permitted only through the remediation path below.
  not_interested: Object.freeze(["queued", "customer", "disqualified", "suppressed"]),
  // A customer is not a prospect any more. The only way out is suppression
  // (they left and asked not to be contacted) — never back into a calling queue.
  customer: Object.freeze(["suppressed"]),
  disqualified: Object.freeze(["review_pending", "suppressed"]),

  // Terminal. Suppression is permanent and cross-campaign by design.
  suppressed: Object.freeze([]),
});

// TRANSITIONS THAT NEED AN ADMINISTRATIVE DECISION, NOT JUST AN ACTOR.
//
// Every transition already records who and why. These few additionally require
// a named approver and a justification, because they re-approach a business
// that has already given or received an answer — the class of move that must
// never happen because a scheduler had a spare slot.
//
// `suppressed` is deliberately absent: it is not remediable, it is terminal.
// A suppression added in error is superseded by a `manual_exclusion` note
// explaining the error (see acquisition-suppression.js); the business is not
// resurrected, because the one bug you cannot recover from is un-suppressing
// somebody who opted out.
const REMEDIATION_TRANSITIONS = Object.freeze({
  "not_interested->queued": "Re-approaching a business that already said no.",
  "not_interested->customer": "Recording a sale to a business that declined — confirm this is not the wrong record.",
  "disqualified->review_pending": "Reopening a business we previously decided not to pursue.",
});

const REMEDIATION_KEY = (from, to) => `${from}->${to}`;

// ── Review ──────────────────────────────────────────────────────────

const REVIEW_DECISIONS = Object.freeze(["approve", "reject", "needs_more_evidence"]);

// Why a reviewer rejected something. A free-text-only rejection is useless for
// improving the pipeline; a coded reason lets the dataset be measured.
const REVIEW_REJECTION_REASONS = Object.freeze([
  "not_a_locksmith",
  "not_trading",
  "wrong_region",
  "source_not_official",
  "evidence_insufficient",
  "identity_ambiguous",
  "phone_unverifiable",
  "already_a_client",
  "do_not_contact",
  "other",
]);

const REVIEW_REJECTION_LABELS = Object.freeze({
  not_a_locksmith: "Not actually a locksmith business",
  not_trading: "No longer trading",
  wrong_region: "Outside the pilot region",
  source_not_official: "No official source for this business",
  evidence_insufficient: "Not enough evidence to be confident",
  identity_ambiguous: "Cannot tell which business this is",
  phone_unverifiable: "Phone number cannot be tied to this business",
  already_a_client: "Already an AIDA client",
  do_not_contact: "Has asked not to be contacted",
  other: "Other reason",
});

// ── Suppression ─────────────────────────────────────────────────────

// Why a number or business may never be called. Append-only and permanent —
// there is no "unsuppress" in the domain model, deliberately.
const SUPPRESSION_REASONS = Object.freeze([
  "opt_out", // they asked not to be called
  "complaint", // they complained
  "regulator_mention", // they mentioned ACMA/OAIC — highest severity
  "manual_exclusion", // founder/lawyer curated
  "competitor", // do not approach
  "existing_client", // already ours
  "wrong_number", // the number does not reach this business
  "dncr_listed", // on the Do Not Call Register with no lawful basis
]);

const SUPPRESSION_REASON_LABELS = Object.freeze({
  opt_out: "Asked not to be contacted",
  complaint: "Made a complaint",
  regulator_mention: "Mentioned a regulator",
  manual_exclusion: "Manually excluded",
  competitor: "Competitor",
  existing_client: "Existing client",
  wrong_number: "Wrong number",
  dncr_listed: "Listed on the Do Not Call Register",
});

// Suppressions that apply to the BUSINESS (every number it has), rather than
// only to the number that triggered them. An opt-out is a statement about the
// relationship, not about a handset.
const BUSINESS_WIDE_SUPPRESSIONS = Object.freeze([
  "opt_out",
  "complaint",
  "regulator_mention",
  "manual_exclusion",
  "competitor",
  "existing_client",
]);

// ── Phone classification ────────────────────────────────────────────

const PHONE_KINDS = Object.freeze([
  "mobile", // 04xx
  "landline", // 02/03/07/08
  "service", // 1300 / 1800
  "premium", // 190x — never called
  "short", // 13xxxx and similar — not a dialable prospect target
  "invalid",
]);

const PHONE_KIND_LABELS = Object.freeze({
  mobile: "Mobile",
  landline: "Landline",
  service: "1300/1800 service number",
  premium: "Premium-rate number",
  short: "Short service number",
  invalid: "Not a valid Australian number",
});

// Kinds the engine will ever consider calling. Premium and short numbers are
// excluded outright: dialling them can cost the RECIPIENT money or reach a
// switchboard that is not the business.
const CALLABLE_PHONE_KINDS = Object.freeze(["mobile", "landline", "service"]);

// ── DNCR ────────────────────────────────────────────────────────────

const DNCR_RESULTS = Object.freeze([
  "not_listed", // washed, absent from the Register
  "listed", // washed, present on the Register
  "unknown", // never washed, or the wash could not be relied on
]);

const DNCR_RESULT_LABELS = Object.freeze({
  not_listed: "Not on the Do Not Call Register",
  listed: "On the Do Not Call Register",
  unknown: "Not checked against the Do Not Call Register",
});

// ── Eligibility ─────────────────────────────────────────────────────

const ELIGIBILITY_DECISIONS = Object.freeze(["eligible", "not_eligible", "blocked"]);

const ELIGIBILITY_DECISION_LABELS = Object.freeze({
  eligible: "Can be called",
  not_eligible: "Cannot be called yet",
  blocked: "Must never be called",
});

// ── Qualification (M8B) ─────────────────────────────────────────────

// Whether a qualification signal is something we OBSERVED or something we
// CONCLUDED. This split is the whole reason the qualification module exists in
// this shape: "their website lists 24-hour callouts" and "they probably take
// after-hours calls" are different kinds of claim, and a founder ranking
// prospects is entitled to know which one is holding a business up the list.
//
// A fact must be traceable to evidence. An inference must name the facts it was
// drawn from. Neither may be invented.
const SIGNAL_KINDS = Object.freeze(["fact", "inference"]);

// The verdict. `qualified` means "worth approaching if compliance permits" —
// it says nothing about whether we are ALLOWED to call, which is
// acquisition-eligibility's question and only its question.
const QUALIFICATION_VERDICTS = Object.freeze([
  "qualified",
  "not_qualified",
  "insufficient_information",
  "disqualified",
]);

const QUALIFICATION_VERDICT_LABELS = Object.freeze({
  qualified: "Worth approaching",
  not_qualified: "Does not clear the bar",
  insufficient_information: "We do not know enough to say",
  disqualified: "Ruled out",
});

// Bands, not a percentage. A tier is a decision a person can argue with; a
// score of 0.72 invites tuning until the number says what somebody wanted.
// The numeric score exists only to ORDER prospects within the same tier, and
// it is always returned alongside the signals that produced it.
const QUALIFICATION_TIERS = Object.freeze(["priority", "standard", "marginal", "excluded"]);

const QUALIFICATION_TIER_LABELS = Object.freeze({
  priority: "Priority — strong fit, approach first",
  standard: "Standard — a good fit",
  marginal: "Marginal — approach only when the list is thin",
  excluded: "Excluded — do not approach",
});

// Reasons a business is ruled out of the locksmith vertical outright. These are
// not score penalties: no amount of other merit overturns them, so they are a
// separate concept from the signal table.
const DISQUALIFIER_CODES = Object.freeze([
  "not_a_locksmith", // the trade evidence says it does something else
  "lead_generation_page", // an SEO funnel that resells calls, not a locksmith
  "national_call_centre", // a switchboard, not a local operator
  "outside_target_market", // not in a market we serve
  "no_callable_number_kind", // premium/short/invalid — never dialable
  "already_a_client", // ours already
]);

const DISQUALIFIER_LABELS = Object.freeze({
  not_a_locksmith: "The evidence does not show a locksmith business",
  lead_generation_page: "A lead-generation page, not a locksmith",
  national_call_centre: "A national call centre rather than a local operator",
  outside_target_market: "Outside the markets we serve",
  no_callable_number_kind: "No number of a kind we would ever dial",
  already_a_client: "Already an AIDA client",
});

// ── Call queue (M8B) ────────────────────────────────────────────────

// Why a prospect was not returned by a queue selection. Distinct from
// eligibility codes on purpose: these are QUEUE reasons ("somebody else has
// it", "it is already in flight"), not permission reasons.
const QUEUE_SKIP_CODES = Object.freeze([
  "not_eligible", // the eligibility engine said no, re-checked just now
  "not_qualified", // commercial fit, not legal permission
  "already_leased", // another worker holds it
  "already_engaged", // it has moved past `queued` in the lifecycle
  "lifecycle_not_queueable", // it is not in a state a call can start from
]);

const QUEUE_SKIP_LABELS = Object.freeze({
  not_eligible: "Not currently allowed to be called",
  not_qualified: "Does not meet the qualification bar",
  already_leased: "Already handed to another worker",
  already_engaged: "Already being worked",
  lifecycle_not_queueable: "Not in a state a call can start from",
});

// The lifecycle states a queue selection may draw from. Deliberately short:
// only a record a human approved, or one released back after a failed attempt
// or a requested callback, may be picked up.
const QUEUEABLE_STATES = Object.freeze(["review_approved", "queued", "attempted", "callback_requested"]);

// ── Campaign batches ────────────────────────────────────────────────

const BATCH_STATES = Object.freeze([
  "draft", // being assembled
  "awaiting_approval", // presented to the founder
  "approved", // founder said yes; AIDA may call later
  "rejected", // founder said no
  "expired", // approval went stale before it was used
  "cancelled", // withdrawn
]);

const BATCH_STATE_LABELS = Object.freeze({
  draft: "Being put together",
  awaiting_approval: "Waiting for your approval",
  approved: "Approved for calling",
  rejected: "You rejected this batch",
  expired: "Approval expired",
  cancelled: "Cancelled",
});

const BATCH_TRANSITIONS = Object.freeze({
  draft: Object.freeze(["awaiting_approval", "cancelled"]),
  awaiting_approval: Object.freeze(["approved", "rejected", "cancelled"]),
  // An approved batch can only decay or be pulled — never re-opened for edits,
  // because the thing the founder approved was a specific list of businesses.
  approved: Object.freeze(["expired", "cancelled"]),
  rejected: Object.freeze([]),
  expired: Object.freeze([]),
  cancelled: Object.freeze([]),
});

module.exports = {
  SCHEMA_VERSION,

  DISCOVERY_ORIGINS,
  DISCOVERY_ORIGIN_LABELS,

  SOURCE_TYPES,
  SOURCE_TYPE_LABELS,
  OFFICIAL_SOURCE_TYPES,
  SOURCE_AUTHORITY_ORDER,

  EVIDENCE_KINDS,
  EVIDENCE_KIND_LABELS,
  CAPTURE_MODES,
  REQUIRED_EVIDENCE_KINDS,

  PROSPECT_STATES,
  PROSPECT_STATE_LABELS,
  PROSPECT_TRANSITIONS,
  ENGAGEMENT_STATES,
  REMEDIATION_TRANSITIONS,
  REMEDIATION_KEY,

  SIGNAL_KINDS,
  QUALIFICATION_VERDICTS,
  QUALIFICATION_VERDICT_LABELS,
  QUALIFICATION_TIERS,
  QUALIFICATION_TIER_LABELS,
  DISQUALIFIER_CODES,
  DISQUALIFIER_LABELS,

  QUEUE_SKIP_CODES,
  QUEUE_SKIP_LABELS,
  QUEUEABLE_STATES,

  REVIEW_DECISIONS,
  REVIEW_REJECTION_REASONS,
  REVIEW_REJECTION_LABELS,

  SUPPRESSION_REASONS,
  SUPPRESSION_REASON_LABELS,
  BUSINESS_WIDE_SUPPRESSIONS,

  PHONE_KINDS,
  PHONE_KIND_LABELS,
  CALLABLE_PHONE_KINDS,

  DNCR_RESULTS,
  DNCR_RESULT_LABELS,

  ELIGIBILITY_DECISIONS,
  ELIGIBILITY_DECISION_LABELS,

  BATCH_STATES,
  BATCH_STATE_LABELS,
  BATCH_TRANSITIONS,
};
